name: Deploy beta to Google

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install libraries
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: install firebase
        run: npm i firebase-tools -g
      - name: install vue cli
        run: npm install -g @vue/cli
      - name: Build
        run: npm run build
      - name: deploy
        run: firebase deploy --only hosting:beta --token ${{ secrets.FIREBASE_TOKEN }}
